name: API Tests

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run tests
        run: |
          newman run postman/collections/restful-booker.collection.json \
          -e postman/environments/dev.environment.json \
          -r cli